from dataclasses import dataclass
from typing import Optional
from datetime import date


@dataclass
class Listing:
    id: int
    listing_url: Optional[str]
    scrape_id: Optional[float]
    last_scraped: Optional[date]
    source: Optional[str]
    name: Optional[str]
    description: Optional[str]
    neighborhood_overview: Optional[str]
    picture_url: Optional[str]
    host_id: Optional[int]
    host_url: Optional[str]
    host_name: Optional[str]
    host_since: Optional[date]
    host_location: Optional[str]
    host_about: Optional[str]
    host_response_time: Optional[str]
    host_response_rate: Optional[str]
    host_acceptance_rate: Optional[int]
    host_is_superhost: Optional[bool]
    host_thumbnail_url: Optional[str]
    host_picture_url: Optional[str]
    host_listings_count: Optional[int]
    host_total_listings_count: Optional[int]
    host_verifications: Optional[str]
    host_has_profile_pic: Optional[bool]
    host_identity_verified: Optional[bool]
    neighbourhood: Optional[str]
    neighbourhood_cleansed: Optional[str]
    neighbourhood_group_cleansed: Optional[str]
    latitude: Optional[float]
    longitude: Optional[float]
    property_type: Optional[str]
    room_type: Optional[str]
    accommodates: Optional[int]
    bathrooms: Optional[float]
    bedrooms: Optional[float]
    beds: Optional[float]
    amenities: Optional[list[str]]
    price: Optional[float]
    minimum_nights: Optional[int]
    maximum_nights: Optional[int]
    minimum_minimum_nights: Optional[int]
    maximum_minimum_nights: Optional[int]
    minimum_maximum_nights: Optional[int]
    maximum_maximum_nights: Optional[int]
    minimum_nights_avg_ntm: Optional[float]
    maximum_nights_avg_ntm: Optional[float]
    has_availability: Optional[bool]
    availability_30: Optional[int]
    availability_60: Optional[int]
    availability_90: Optional[int]
    availability_365: Optional[int]
    calendar_last_scraped: Optional[date]
    number_of_reviews: Optional[int]
    number_of_reviews_ltm: Optional[int]
    number_of_reviews_l30d: Optional[int]
    first_review: Optional[date]
    last_review: Optional[date]
    review_scores_rating: Optional[float]
    review_scores_accuracy: Optional[float]
    review_scores_cleanliness: Optional[float]
    review_scores_checkin: Optional[float]
    review_scores_communication: Optional[float]
    review_scores_location: Optional[float]
    review_scores_value: Optional[float]
    instant_bookable: Optional[bool]
    calculated_host_listings_count: Optional[int]
    calculated_host_listings_count_entire_homes: Optional[int]
    calculated_host_listings_count_private_rooms: Optional[int]
    reviews_per_month: Optional[float]
    missing_data_flag: Optional[bool]



